/**
 * Animation Presets
 * Pre-configured animation templates for common use cases
 */

const ANIMATION_PRESETS = {
    // Entrance animations
    fadeIn: {
        name: "Fade In",
        category: "entrance",
        type: "fadeIn",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startOpacity: 0,
        endOpacity: 1,
    },
    slideInUp: {
        name: "Slide In Up",
        category: "entrance",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        direction: "up",
        startOpacity: 0,
        endOpacity: 1,
    },
    slideInDown: {
        name: "Slide In Down",
        category: "entrance",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        direction: "down",
        startOpacity: 0,
        endOpacity: 1,
    },
    slideInLeft: {
        name: "Slide In Left",
        category: "entrance",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        direction: "left",
        startOpacity: 0,
        endOpacity: 1,
    },
    slideInRight: {
        name: "Slide In Right",
        category: "entrance",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        direction: "right",
        startOpacity: 0,
        endOpacity: 1,
    },
    zoomIn: {
        name: "Zoom In",
        category: "entrance",
        type: "scaleInPlace",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startScale: 0.5,
        startOpacity: 0,
        endScale: 1,
        endOpacity: 1,
    },
    popIn: {
        name: "Pop In",
        category: "entrance",
        type: "scaleInPlace",
        duration: 400,
        delay: 0,
        easing: "easeOut",
        startScale: 0.3,
        startOpacity: 0,
        endScale: 1,
        endOpacity: 1,
    },
    bounce: {
        name: "Bounce In",
        category: "entrance",
        type: "scaleInPlace",
        duration: 800,
        delay: 0,
        easing: "easeOutElastic",
        startScale: 0,
        startOpacity: 0,
        endScale: 1,
        endOpacity: 1,
    },

    // Exit animations
    fadeOut: {
        name: "Fade Out",
        category: "exit",
        type: "fadeOut",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        startOpacity: 1,
        endOpacity: 0,
    },
    slideOutUp: {
        name: "Slide Out Up",
        category: "exit",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        direction: "up",
        startOpacity: 1,
        endOpacity: 0,
    },
    slideOutDown: {
        name: "Slide Out Down",
        category: "exit",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        direction: "down",
        startOpacity: 1,
        endOpacity: 0,
    },
    slideOutLeft: {
        name: "Slide Out Left",
        category: "exit",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        direction: "left",
        startOpacity: 1,
        endOpacity: 0,
    },
    slideOutRight: {
        name: "Slide Out Right",
        category: "exit",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        direction: "right",
        startOpacity: 1,
        endOpacity: 0,
    },
    zoomOut: {
        name: "Zoom Out",
        category: "exit",
        type: "scaleInPlace",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        startScale: 1,
        startOpacity: 1,
        endScale: 0,
        endOpacity: 0,
    },

    // Emphasis animations
    pulse: {
        name: "Pulse",
        category: "emphasis",
        type: "scaleInPlace",
        duration: 600,
        delay: 0,
        easing: "easeInOut",
        startScale: 1,
        endScale: 1.1,
    },
    rotate: {
        name: "Rotate",
        category: "emphasis",
        type: "rotate",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        rotation: 360,
    },
    spin: {
        name: "Spin",
        category: "emphasis",
        type: "rotate",
        duration: 1000,
        delay: 0,
        easing: "linear",
        rotation: 360,
    },

    // Scientific presets
    drawPath: {
        name: "Draw Path",
        category: "scientific",
        type: "write",
        duration: 1200,
        delay: 0,
        easing: "easeOut",
    },
    createObject: {
        name: "Create",
        category: "scientific",
        type: "create",
        duration: 800,
        delay: 0,
        easing: "easeOut",
        startOpacity: 0,
        endOpacity: 1,
    },
    uncreateObject: {
        name: "Uncreate",
        category: "scientific",
        type: "uncreate",
        duration: 800,
        delay: 0,
        easing: "easeIn",
        startOpacity: 1,
        endOpacity: 0,
    },

    // Cinematic presets
    cinematicEnter: {
        name: "Cinematic Enter",
        category: "cinematic",
        type: "scaleInPlace",
        duration: 1200,
        delay: 0,
        easing: "easeOutBack",
        startScale: 0.8,
        startOpacity: 0,
        endScale: 1,
        endOpacity: 1,
    },
    cinematicExit: {
        name: "Cinematic Exit",
        category: "cinematic",
        type: "scaleInPlace",
        duration: 1200,
        delay: 0,
        easing: "easeInBack",
        startScale: 1,
        startOpacity: 1,
        endScale: 0.8,
        endOpacity: 0,
    },

    // Minimal presets
    subtleEnter: {
        name: "Subtle Enter",
        category: "minimal",
        type: "fadeIn",
        duration: 300,
        delay: 0,
        easing: "easeOut",
        startOpacity: 0.7,
        endOpacity: 1,
    },
    subtleExit: {
        name: "Subtle Exit",
        category: "minimal",
        type: "fadeOut",
        duration: 300,
        delay: 0,
        easing: "easeIn",
        startOpacity: 1,
        endOpacity: 0.7,
    },
    // NEW: Color animations
    colorFadeFromRed: {
        name: "Color Fade (Red → Neutral)",
        category: "color",
        type: "colorShift",
        duration: 800,
        delay: 0,
        easing: "easeInOut",
        startColor: "#ff4444",
        endColor: "#000000",
        colorProperty: "fill",
    },
    colorPulse: {
        name: "Color Pulse",
        category: "color",
        type: "colorShift",
        duration: 600,
        delay: 0,
        easing: "easeInOut",
        startColor: "#4488ff",
        endColor: "#44ffff",
        colorProperty: "fill",
    },
    highlightBlink: {
        name: "Highlight Blink",
        category: "color",
        type: "colorShift",
        duration: 400,
        delay: 0,
        easing: "easeOut",
        startColor: "#ffff00",
        endColor: "#000000",
        colorProperty: "fill",
    },
    // NEW: Position animations
    moveRight: {
        name: "Move Right",
        category: "position",
        type: "moveInPlace",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startX: 0,
        endX: 100,
        startY: 0,
        endY: 0,
    },
    moveUp: {
        name: "Move Up",
        category: "position",
        type: "moveInPlace",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startX: 0,
        endX: 0,
        startY: 0,
        endY: -100,
    },
    floatAround: {
        name: "Float Around",
        category: "position",
        type: "moveInPlace",
        duration: 1200,
        delay: 0,
        easing: "easeInOut",
        startX: 0,
        endX: 50,
        startY: 0,
        endY: -30,
    },
    // NEW: Scale animations
    scaleUpDown: {
        name: "Scale Up & Down",
        category: "scale",
        type: "scaleXY",
        duration: 800,
        delay: 0,
        easing: "easeInOut",
        startScaleX: 1,
        endScaleX: 1.2,
        startScaleY: 1,
        endScaleY: 0.9,
    },
    stretchHorizontal: {
        name: "Stretch Horizontal",
        category: "scale",
        type: "scaleXY",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startScaleX: 0.5,
        endScaleX: 1,
        startScaleY: 1,
        endScaleY: 1,
    },
    // NEW: SVG stroke animations
    strokeDraw: {
        name: "Stroke Draw",
        category: "svg",
        type: "strokeAnimate",
        duration: 1000,
        delay: 0,
        easing: "easeOut",
        startStrokeWidth: 0,
        endStrokeWidth: 2,
    },
    strokeThicken: {
        name: "Stroke Thicken",
        category: "svg",
        type: "strokeAnimate",
        duration: 500,
        delay: 0,
        easing: "easeInOut",
        startStrokeWidth: 1,
        endStrokeWidth: 4,
    },
    // NEW: Combined transforms
    slideAndGrow: {
        name: "Slide & Grow",
        category: "advanced",
        type: "combinedTransform",
        duration: 800,
        delay: 0,
        easing: "easeOut",
        startX: -100,
        endX: 0,
        startY: 0,
        endY: 0,
        startScaleX: 0.5,
        endScaleX: 1,
        startScaleY: 0.5,
        endScaleY: 1,
        startRotation: -10,
        endRotation: 0,
    },
    spinAndMove: {
        name: "Spin & Move",
        category: "advanced",
        type: "combinedTransform",
        duration: 1000,
        delay: 0,
        easing: "easeOut",
        startX: 0,
        endX: 150,
        startY: 0,
        endY: -50,
        startScaleX: 1,
        endScaleX: 1,
        startScaleY: 1,
        endScaleY: 1,
        startRotation: 0,
        endRotation: 360,
    },

    // ADVANCED: Morphing and transformation
    replacementTransformSmooth: {
        name: "Smooth Morph",
        category: "advanced",
        type: "replacementTransform",
        duration: 800,
        delay: 0,
        easing: "easeInOut",
        startGeometry: { width: 100, height: 100, x: 0, y: 0 },
        endGeometry: { width: 100, height: 100, x: 0, y: 0 },
        startColor: "#4488ff",
        endColor: "#ff4488",
        startOpacity: 1,
        endOpacity: 1,
        startScale: 1,
        endScale: 1.2,
        startRotation: 0,
        endRotation: 360,
    },

    // ADVANCED: Path animations
    trajectorySmooth: {
        name: "Smooth Trajectory",
        category: "scientific",
        type: "moveAlongPath",
        duration: 2000,
        delay: 0,
        easing: "easeInOut",
        pathType: "bezier",
        controlPoints: {
            start: { x: 0, y: 0 },
            cp1: { x: 100, y: -100 },
            cp2: { x: 200, y: -100 },
            end: { x: 300, y: 0 },
        },
        followPath: true,
    },

    // ADVANCED: Text morphing
    textReveal: {
        name: "Text Reveal",
        category: "scientific",
        type: "textMorph",
        duration: 1000,
        delay: 0,
        easing: "easeOut",
        startText: "",
        endText: "",
        morphMode: "letter-by-letter",
        startColor: "#000000",
        endColor: "#000000",
        startOpacity: 0,
        endOpacity: 1,
        startScale: 1,
        endScale: 1,
    },

    // ADVANCED: Emphasis effects
    pulseEmphasis: {
        name: "Pulse Emphasis",
        category: "emphasis",
        type: "emphasis",
        duration: 600,
        delay: 0,
        easing: "easeInOut",
        emphasisType: "pulse",
        cycles: 2,
        intensity: 0.2,
    },

    wiggleEmphasis: {
        name: "Wiggle Emphasis",
        category: "emphasis",
        type: "emphasis",
        duration: 600,
        delay: 0,
        easing: "easeInOut",
        emphasisType: "wiggle",
        cycles: 1,
        amplitude: 10,
    },

    bounceEmphasis: {
        name: "Bounce Emphasis",
        category: "emphasis",
        type: "emphasis",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        emphasisType: "bounce",
        cycles: 1,
        intensity: 0.3,
    },

    heartbeatEmphasis: {
        name: "Heartbeat Emphasis",
        category: "emphasis",
        type: "emphasis",
        duration: 600,
        delay: 0,
        easing: "easeInOut",
        emphasisType: "heartbeat",
        cycles: 2,
        intensity: 0.15,
    },

    // ADVANCED: Blur animations
    blurInFocus: {
        name: "Blur In Focus",
        category: "advanced",
        type: "blur",
        duration: 800,
        delay: 0,
        easing: "easeOut",
        direction: "in",
        startBlur: 15,
        endBlur: 0,
        startOpacity: 0.5,
        endOpacity: 1,
    },

    blurOutOfFocus: {
        name: "Blur Out of Focus",
        category: "advanced",
        type: "blur",
        duration: 800,
        delay: 0,
        easing: "easeIn",
        direction: "out",
        startBlur: 0,
        endBlur: 15,
        startOpacity: 1,
        endOpacity: 0.5,
    },

    // ADVANCED: 3D effects
    flip3DHorizontal: {
        name: "3D Flip (Horizontal)",
        category: "advanced",
        type: "flip3D",
        duration: 800,
        delay: 0,
        easing: "easeInOut",
        axis: "y",
        rotation: 180,
        perspective: 1000,
    },

    flip3DVertical: {
        name: "3D Flip (Vertical)",
        category: "advanced",
        type: "flip3D",
        duration: 800,
        delay: 0,
        easing: "easeInOut",
        axis: "x",
        rotation: 180,
        perspective: 1000,
    },

    // ADVANCED: Glow effects
    glowHighlight: {
        name: "Glow Highlight",
        category: "emphasis",
        type: "glow",
        duration: 1000,
        delay: 0,
        easing: "easeInOut",
        glowColor: "#ffff00",
        startBlur: 5,
        peakBlur: 25,
        pulses: 2,
    },

    energyGlow: {
        name: "Energy Glow",
        category: "scientific",
        type: "glow",
        duration: 1500,
        delay: 0,
        easing: "easeInOut",
        glowColor: "#44ff44",
        startBlur: 3,
        peakBlur: 30,
        pulses: 3,
    },

    // ADVANCED: Advanced uncreate
    uncreateExplode: {
        name: "Explode Out",
        category: "exit",
        type: "uncreateAdvanced",
        duration: 800,
        delay: 0,
        easing: "easeOut",
        destructionMode: "explode",
        startOpacity: 1,
        endOpacity: 0,
        explosionVelocity: 10,
    },

    uncreateShrink: {
        name: "Shrink Out",
        category: "exit",
        type: "uncreateAdvanced",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        destructionMode: "shrink",
        startOpacity: 1,
        endOpacity: 0,
    },

    // Backward-compatible alias for existing saved references/tests. Hidden from the picker, which listed
    // "Shrink Out" twice.
    uncreaeShrink: {
        name: "Shrink Out",
        alias: true,
        category: "exit",
        type: "uncreateAdvanced",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        destructionMode: "shrink",
        startOpacity: 1,
        endOpacity: 0,
    },

    // ANIMATED CHARTS
    chartBarsReveal: {
        name: "Chart Bars Reveal",
        category: "scientific",
        type: "animatedChart",
        duration: 1500,
        delay: 0,
        easing: "easeOut",
        chartType: "bar",
        animationMode: "staggered",
        staggerDelay: 150,
        direction: "from-zero",
    },

    chartLinesDraw: {
        name: "Chart Lines Draw",
        category: "scientific",
        type: "animatedChart",
        duration: 2000,
        delay: 0,
        easing: "easeInOut",
        chartType: "line",
        animationMode: "progressive",
        lineDrawMode: "stroke-dash",
    },

    scatterPointsReveal: {
        name: "Scatter Points Appear",
        category: "scientific",
        type: "animatedChart",
        duration: 1200,
        delay: 0,
        easing: "easeOut",
        chartType: "scatter",
        animationMode: "staggered",
        staggerDelay: 100,
    },

    // IMPROVED: Elegant Fade Animations
    elegantFadeIn: {
        name: "Elegant Fade In",
        category: "entrance",
        type: "elegantFadeIn",
        duration: 300,
        delay: 0,
        easing: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        startOpacity: 0,
        endOpacity: 1,
        startScale: 0.95,
        endScale: 1,
    },
    elegantFadeOut: {
        name: "Elegant Fade Out",
        category: "exit",
        type: "elegantFadeOut",
        duration: 280,
        delay: 0,
        easing: "cubic-bezier(0.7, 0, 1, 0.3)",
        startOpacity: 1,
        endOpacity: 0,
        startScale: 1,
        endScale: 0.92,
    },
    fadeWithBlurIn: {
        name: "Fade with Blur In",
        category: "entrance",
        type: "fadeWithBlur",
        duration: 350,
        delay: 0,
        easing: "cubic-bezier(0.16, 1, 0.3, 1)",
        startOpacity: 0,
        endOpacity: 1,
        startBlur: 16,
        endBlur: 0,
    },
    fadeWithBlurOut: {
        name: "Fade with Blur Out",
        category: "exit",
        type: "fadeWithBlur",
        duration: 340,
        delay: 0,
        easing: "cubic-bezier(0.7, 0, 1, 0.3)",
        startOpacity: 1,
        endOpacity: 0,
        startBlur: 0,
        endBlur: 16,
    },

    // NEW: Diffuse/Particle Animations (Industry-Standard Timing)
    diffuseSparkle: {
        name: "Diffuse Sparkle",
        category: "advanced",
        type: "diffuse",
        duration: 500,
        delay: 0,
        easing: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        diffuseType: "sparkle",
        startOpacity: 1,
        endOpacity: 0,
        startIntensity: 1,
        endIntensity: 0,
        particleCount: 10,
        particleColor: "rgba(255, 200, 100, 0.9)",
        disperseDistance: 80,
        staggerDelay: 50,
    },
    diffuseWave: {
        name: "Diffuse Wave",
        category: "advanced",
        type: "diffuse",
        duration: 520,
        delay: 0,
        easing: "cubic-bezier(0.43, 0.13, 0.23, 0.96)",
        diffuseType: "wave",
        startOpacity: 1,
        endOpacity: 0,
        startIntensity: 1,
        endIntensity: 0,
        particleCount: 12,
        particleColor: "rgba(100, 150, 255, 0.85)",
        disperseDistance: 100,
        waveLength: 8,
        staggerDelay: 50,
    },
    diffuseSmoke: {
        name: "Diffuse Smoke",
        category: "advanced",
        type: "diffuse",
        duration: 550,
        delay: 0,
        easing: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        diffuseType: "smoke",
        startOpacity: 1,
        endOpacity: 0,
        startIntensity: 1,
        endIntensity: 0,
        particleCount: 12,
        particleColor: "rgba(150, 150, 150, 0.75)",
        disperseDistance: 120,
        staggerDelay: 50,
    },
    diffuseDissolve: {
        name: "Diffuse Dissolve",
        category: "advanced",
        type: "diffuse",
        duration: 480,
        delay: 0,
        easing: "cubic-bezier(0.43, 0.13, 0.23, 0.96)",
        diffuseType: "dissolve",
        startOpacity: 1,
        endOpacity: 0,
        startIntensity: 1,
        endIntensity: 0,
        particleCount: 10,
        particleColor: "rgba(200, 200, 255, 0.8)",
        disperseDistance: 75,
        staggerDelay: 50,
    },
};

const PRESET_CATEGORIES = {
    entrance: {
        name: "Entrance",
        icon: "arrow-right",
        description: "Animations for objects appearing",
    },
    exit: {
        name: "Exit",
        icon: "arrow-left",
        description: "Animations for objects disappearing",
    },
    emphasis: {
        name: "Emphasis",
        icon: "star",
        description: "Animations for emphasis",
    },
    scientific: {
        name: "Scientific",
        icon: "microscope",
        description: "Animations for scientific visualization",
    },
    cinematic: {
        name: "Cinematic",
        icon: "film",
        description: "Cinematic motion effects",
    },
    minimal: {
        name: "Minimal",
        icon: "minimize-2",
        description: "Subtle, refined animations",
    },
    color: {
        name: "Color",
        icon: "palette",
        description: "Color shift and transition animations",
    },
    position: {
        name: "Position",
        icon: "move",
        description: "Movement and position animations",
    },
    scale: {
        name: "Scale",
        icon: "maximize-2",
        description: "Scale and stretch animations",
    },
    svg: {
        name: "SVG / Stroke",
        icon: "pen-tool",
        description: "SVG path and stroke animations",
    },
    advanced: {
        name: "Advanced",
        icon: "cpu",
        description: "Advanced morphing, blur, and 3D effects",
    },
};

function getPreset(presetName) {
    return ANIMATION_PRESETS[presetName] || null;
}

function getPresetsByCategory(category) {
    return Object.entries(ANIMATION_PRESETS)
        .filter(([_, preset]) => preset.category === category && !preset.alias)
        .map(([id, preset]) => ({ id, ...preset }));
}

function getAllPresets() {
    return Object.entries(ANIMATION_PRESETS).map(([id, preset]) => ({ id, ...preset }));
}

function createPresetAnimation(presetName, overrides = {}) {
    const preset = getPreset(presetName);
    if (!preset) return null;

    return {
        ...preset,
        ...overrides,
        id: generateId("anim"),
        trigger: overrides.trigger === "on-click" ? "on-click" : preset.trigger || "on-slide",
        delay: Math.max(0, Number(overrides.delay ?? preset.delay) || 0),
        duration: Math.max(100, Number(overrides.duration ?? preset.duration) || 600),
    };
}

// Export presets
if (typeof module !== "undefined" && module.exports) {
    module.exports = {
        ANIMATION_PRESETS,
        PRESET_CATEGORIES,
        getPreset,
        getPresetsByCategory,
        getAllPresets,
        createPresetAnimation,
    };
}
