import { GRAPH_DOMAINS, GRAPH_NODE_ROLES } from "./semanticRoles.js";

export const GRAPH_NODE_TYPES = Object.freeze({
    PROCESS: "process",
    DECISION: "decision",
    DATABASE: "database",
    QUEUE: "queue",
    ACTOR: "actor",
    DOCUMENT: "document",
    SCIENTIFIC: "scientific",
    MEDIA: "media",
    ANNOTATION: "annotation",
});

export const SCIENTIFIC_NODE_TYPES = Object.freeze({
    MD_MINIMIZATION: {
        subtype: "md-minimization",
        label: "Energy minimization",
        domain: GRAPH_DOMAINS.MOLECULAR_DYNAMICS,
        role: "simulation-preparation",
        shape: "scientific",
        suggestedNext: ["md-equilibration"],
    },
    MD_EQUILIBRATION: {
        subtype: "md-equilibration",
        label: "Equilibration",
        domain: GRAPH_DOMAINS.MOLECULAR_DYNAMICS,
        role: "simulation-preparation",
        shape: "scientific",
        suggestedNext: ["md-production-run"],
    },
    MD_PRODUCTION: {
        subtype: "md-production-run",
        label: "Production MD",
        domain: GRAPH_DOMAINS.MOLECULAR_DYNAMICS,
        role: "simulation",
        shape: "scientific",
        suggestedNext: ["trajectory-processing", "enhanced-sampling"],
    },
    ENHANCED_SAMPLING: {
        subtype: "enhanced-sampling",
        label: "Enhanced sampling",
        domain: GRAPH_DOMAINS.ENHANCED_SAMPLING,
        role: "sampling",
        shape: "hexagon",
        suggestedNext: ["free-energy-calculation"],
    },
    PATH_CV: {
        subtype: "pathcv",
        label: "PathCV",
        domain: GRAPH_DOMAINS.ENHANCED_SAMPLING,
        role: "collective-variable",
        shape: "hexagon",
        suggestedNext: ["free-energy-calculation"],
    },
    WE_BINNING: {
        subtype: "we-binning",
        label: "WE binning",
        domain: GRAPH_DOMAINS.WEIGHTED_ENSEMBLE,
        role: "weighted-ensemble-binning",
        shape: "queue",
        suggestedNext: ["msm-analysis"],
    },
    MSM_ANALYSIS: {
        subtype: "msm-analysis",
        label: "MSM analysis",
        domain: GRAPH_DOMAINS.KINETICS,
        role: GRAPH_NODE_ROLES.ANALYSIS,
        shape: "process",
        suggestedNext: ["figure-generation"],
    },
    CLUSTERING: {
        subtype: "clustering",
        label: "Clustering",
        domain: GRAPH_DOMAINS.KINETICS,
        role: GRAPH_NODE_ROLES.ANALYSIS,
        shape: "process",
        suggestedNext: ["msm-analysis"],
    },
    FREE_ENERGY: {
        subtype: "free-energy-calculation",
        label: "Free energy calculation",
        domain: GRAPH_DOMAINS.FREE_ENERGY,
        role: GRAPH_NODE_ROLES.ANALYSIS,
        shape: "process",
        suggestedNext: ["figure-generation"],
    },
    GPU_CLUSTER: {
        subtype: "gpu-cluster",
        label: "GPU cluster",
        domain: GRAPH_DOMAINS.COMPUTATIONAL_PIPELINE,
        role: GRAPH_NODE_ROLES.COMPUTE,
        shape: "database",
        suggestedNext: ["scheduler-queue"],
    },
    SCHEDULER_QUEUE: {
        subtype: "scheduler-queue",
        label: "Scheduler queue",
        domain: GRAPH_DOMAINS.COMPUTATIONAL_PIPELINE,
        role: GRAPH_NODE_ROLES.COMPUTE,
        shape: "queue",
        suggestedNext: ["md-production-run"],
    },
    TRAJECTORY_PROCESSING: {
        subtype: "trajectory-processing",
        label: "Trajectory processing",
        domain: GRAPH_DOMAINS.MOLECULAR_DYNAMICS,
        role: GRAPH_NODE_ROLES.DATA,
        shape: "parallelogram",
        suggestedNext: ["clustering", "statistical-analysis"],
    },
    NOTEBOOK: {
        subtype: "analysis-notebook",
        label: "Analysis notebook",
        domain: GRAPH_DOMAINS.COMPUTATIONAL_PIPELINE,
        role: GRAPH_NODE_ROLES.ANALYSIS,
        shape: "document",
        suggestedNext: ["figure-generation"],
    },
    FIGURE_GENERATION: {
        subtype: "figure-generation",
        label: "Figure generation",
        domain: GRAPH_DOMAINS.COMPUTATIONAL_PIPELINE,
        role: GRAPH_NODE_ROLES.FIGURE,
        shape: "document",
        suggestedNext: ["manuscript-stage"],
    },
    MANUSCRIPT: {
        subtype: "manuscript-stage",
        label: "Manuscript",
        domain: GRAPH_DOMAINS.EXPERIMENTAL_DESIGN,
        role: GRAPH_NODE_ROLES.MANUSCRIPT,
        shape: "document",
        suggestedNext: [],
    },
    STATISTICS: {
        subtype: "statistical-analysis",
        label: "Statistical analysis",
        domain: GRAPH_DOMAINS.EXPERIMENTAL_DESIGN,
        role: GRAPH_NODE_ROLES.ANALYSIS,
        shape: "process",
        suggestedNext: ["experimental-validation", "figure-generation"],
    },
    VALIDATION: {
        subtype: "experimental-validation",
        label: "Experimental validation",
        domain: GRAPH_DOMAINS.EXPERIMENTAL_DESIGN,
        role: GRAPH_NODE_ROLES.VALIDATION,
        shape: "decision",
        suggestedNext: ["manuscript-stage"],
    },
    DATABASE_IMPORT: {
        subtype: "database-import",
        label: "Database import",
        domain: GRAPH_DOMAINS.COMPUTATIONAL_PIPELINE,
        role: GRAPH_NODE_ROLES.DATA,
        shape: "database",
        suggestedNext: ["preprocessing"],
    },
    MOLECULAR_PATHWAY: {
        subtype: "molecular-pathway-node",
        label: "Molecular pathway",
        domain: GRAPH_DOMAINS.SYSTEMS_BIOLOGY,
        role: GRAPH_NODE_ROLES.MOLECULAR_PATHWAY,
        shape: "scientific",
        suggestedNext: [],
    },
});
